//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomaddoors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Festival
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Short { get; set; }
        public string About { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Address { get; set; }
        public Nullable<int> Guide { get; set; }
        public string Organizator { get; set; }
        public Nullable<int> Price { get; set; }
        public string Date { get; set; }
        public string Image { get; set; }
    }
}
