//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomaddoors
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int ID { get; set; }
        public Nullable<int> Festival { get; set; }
        public string Time { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
